-- FIAP X - database creation script
--
-- GENERATED by scripts/generate-db-script.mjs. Do not edit by hand:
-- regenerate it instead, or it stops describing the schema that runs.
--
-- Source: db/init/01-schemas.sql, then each service's own migrations.
--
-- This creates the schema the services expect. It does NOT write
-- TypeORM's migrations ledger, so a database created this way will have
-- each service try to apply its migrations again on first start. Use it
-- to inspect or provision the schema, not as a substitute for running
-- migrations against a database the services will then own.

-- ============================================================
-- Schemas and least-privilege roles
-- ============================================================

-- Bootstrap for the local topology.
--
-- RUNS ONLY ONCE, on an empty data volume. The PostgreSQL image executes
-- everything in /docker-entrypoint-initdb.d the first time it initialises a
-- data directory and never again. A developer whose volume predates this file
-- will see the services fail to reach their schema; the fix is
-- `docker compose down -v`. See the README.
--
-- This is bootstrap, not migration. Each service owns and evolves its own
-- tables through its own migrations; this file only creates the empty rooms
-- and locks the doors between them.

-- One schema and one role per owning service. The foundation forbids a service
-- reading another's tables, and a grant is the only form of that rule which
-- survives someone in a hurry.

CREATE SCHEMA IF NOT EXISTS catalog;
CREATE SCHEMA IF NOT EXISTS notification;

-- Roles are cluster-wide, not per-database, so a plain CREATE ROLE fails the
-- moment this script is applied to a second database in the same cluster.
-- The deliverable has to be applicable to an empty database, not only an
-- empty cluster.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'catalog') THEN
    CREATE ROLE catalog LOGIN PASSWORD 'catalog';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'notification') THEN
    CREATE ROLE notification LOGIN PASSWORD 'notification';
  END IF;
END
$$;

-- Each role owns its schema outright, so its migrations can create tables.
ALTER SCHEMA catalog OWNER TO catalog;
ALTER SCHEMA notification OWNER TO notification;

-- current_database() rather than a literal: the deliverable must work in
-- whatever database it is applied to.
DO $$
BEGIN
  EXECUTE format(
    'GRANT CONNECT ON DATABASE %I TO catalog, notification',
    current_database()
  );
END
$$;

-- Neither role may see the other's schema. PUBLIC is revoked first, because
-- otherwise every role would inherit access to anything created later.
REVOKE ALL ON SCHEMA catalog FROM PUBLIC;
REVOKE ALL ON SCHEMA notification FROM PUBLIC;

GRANT USAGE, CREATE ON SCHEMA catalog TO catalog;
GRANT USAGE, CREATE ON SCHEMA notification TO notification;

-- A role's default search path points at its own schema, so a migration that
-- omits the qualifier still lands in the right place.
ALTER ROLE catalog SET search_path TO catalog;
ALTER ROLE notification SET search_path TO notification;

-- ============================================================
-- processing-catalog (schema: catalog)
-- ============================================================

SET search_path TO catalog;

-- from 1789953000000-CreateProcessingRequest.ts
CREATE TABLE IF NOT EXISTS processing_request (
        processing_request_id uuid        PRIMARY KEY,
        owner_user_id         text        NOT NULL,
        source_storage_key    text        NOT NULL,
        status                text        NOT NULL,
        attempt_id            uuid        NULL,
        zip_storage_key       text        NULL,
        failure_code          text        NULL,
        created_at            timestamptz NOT NULL,
        updated_at            timestamptz NOT NULL
      );

CREATE TABLE IF NOT EXISTS processed_event (
        event_id              text        PRIMARY KEY,
        processing_request_id uuid        NULL,
        processed_at          timestamptz NOT NULL
      );

CREATE INDEX IF NOT EXISTS idx_processing_request_owner
        ON processing_request (owner_user_id);

-- from 1789953100000-CreateOutbox.ts
CREATE TABLE IF NOT EXISTS outbox (
        id            bigserial   PRIMARY KEY,
        queue         text        NOT NULL,
        pattern       text        NOT NULL,
        payload       jsonb       NOT NULL,
        created_at    timestamptz NOT NULL,
        published_at  timestamptz NULL
      );

CREATE INDEX IF NOT EXISTS idx_outbox_pending
        ON outbox (id) WHERE published_at IS NULL;

-- from 1789955000000-IndexProcessingRequestOwnerCreatedAt.ts
CREATE INDEX IF NOT EXISTS idx_processing_request_owner_created
        ON processing_request (owner_user_id, created_at DESC, processing_request_id);

DROP INDEX IF EXISTS idx_processing_request_owner;

-- ============================================================
-- notification-service (schema: notification)
-- ============================================================

SET search_path TO notification;

-- from 1789954000000-CreateDeliveryRecord.ts
CREATE TABLE IF NOT EXISTS delivery_record (
        event_id              text        PRIMARY KEY,
        processing_request_id text        NOT NULL,
        owner_user_id         text        NOT NULL,
        status                text        NOT NULL,
        zip_storage_key       text        NULL,
        failure_reason        text        NULL,
        recorded_at           timestamptz NOT NULL
      );

CREATE INDEX IF NOT EXISTS idx_delivery_record_request
        ON delivery_record (processing_request_id);

RESET search_path;
